// <auto-generated />
using System;
using ApiProjectMagangDotnet.AppDbProfile;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProjectMagangDotnet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251019134500_migrationBaru")]
    partial class migrationBaru
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiProjectMagangDotnet.Models.AspUser", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomorHP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("AspUsers");
                });

            modelBuilder.Entity("ApiProjectMagangDotnet.Models.Dokter", b =>
                {
                    b.Property<string>("Id_Dokter")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HariPraktek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("JamMulai")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("JamSelesai")
                        .HasColumnType("time");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoHP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spesialisasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Dokter");

                    b.ToTable("Dokters");
                });

            modelBuilder.Entity("ApiProjectMagangDotnet.Models.Klinik", b =>
                {
                    b.Property<string>("Id_Klinik")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gedung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lantai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Klinik");

                    b.ToTable("Kliniks");
                });

            modelBuilder.Entity("ApiProjectMagangDotnet.Models.Kunjungan", b =>
                {
                    b.Property<string>("Id_Kunjungan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_Dokter")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Klinik")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_RekamMedis")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JenisKunjungan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keluhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoAntrian")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("date");

                    b.HasKey("Id_Kunjungan");

                    b.HasIndex("Id_Dokter");

                    b.HasIndex("Id_Klinik");

                    b.HasIndex(new[] { "Id_RekamMedis", "Id_Dokter", "Id_Klinik", "Tanggal" }, "IX_Unique_Kunjungan")
                        .IsUnique();

                    b.ToTable("Kunjungan");
                });

            modelBuilder.Entity("ApiProjectMagangDotnet.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("ApiProjectMagangDotnet.Models.RekamMedis", b =>
                {
                    b.Property<string>("Id_RekamMedis")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Agama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bahasa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bulan")
                        .HasColumnType("int");

                    b.Property<string>("ButuhPenerjemah")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kabupaten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kecamatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoKTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoTelp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pekerjaan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pendidikan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provinsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusKawin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("TanggalLahir")
                        .HasColumnType("date");

                    b.Property<string>("TempatLahir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Umur")
                        .HasColumnType("int");

                    b.HasKey("Id_RekamMedis");

                    b.ToTable("RekamMediss");
                });

            modelBuilder.Entity("ApiProjectMagangDotnet.Models.UserPasien", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_RekamMedis")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NamaUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomorHP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.HasIndex("Id_RekamMedis");

                    b.ToTable("UserPasiens");
                });

            modelBuilder.Entity("ApiProjectMagangDotnet.Models.Kunjungan", b =>
                {
                    b.HasOne("ApiProjectMagangDotnet.Models.Dokter", "Dokter")
                        .WithMany()
                        .HasForeignKey("Id_Dokter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiProjectMagangDotnet.Models.Klinik", "Klinik")
                        .WithMany()
                        .HasForeignKey("Id_Klinik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiProjectMagangDotnet.Models.RekamMedis", "RekamMedis")
                        .WithMany()
                        .HasForeignKey("Id_RekamMedis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dokter");

                    b.Navigation("Klinik");

                    b.Navigation("RekamMedis");
                });

            modelBuilder.Entity("ApiProjectMagangDotnet.Models.UserPasien", b =>
                {
                    b.HasOne("ApiProjectMagangDotnet.Models.RekamMedis", "RekamMedis")
                        .WithMany()
                        .HasForeignKey("Id_RekamMedis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RekamMedis");
                });
#pragma warning restore 612, 618
        }
    }
}
